CREATE TABLE JPAGEN_ADDRESS (ID NUMBER PRIMARY KEY, CITY VARCHAR(255) NOT NULL, STREET VARCHAR(255) NOT NULL);
CREATE TABLE JPAGEN_PERSON (ID NUMBER PRIMARY KEY, NAME VARCHAR(255) NOT NULL, ADDRESS_ID NUMBER);
ALTER TABLE JPAGEN_PERSON ADD CONSTRAINT JPAGEN_PERSON_ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES JPAGEN_ADDRESS(ID);

CREATE SEQUENCE JPAGEN_ADDRESS_SEQ START WITH 100;
CREATE TABLE JPAGEN_GENERATORS(NAME VARCHAR(255) PRIMARY KEY, VALUE NUMBER);
